//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginFunctionalityMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public long UserID { get; set; }
        public string Username { get; set; }
        public string HASH { get; set; }
        public byte[] SALT { get; set; }
    }
}
